# Generated by Django 4.1 on 2022-09-20 10:58

import audio_recordings_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recordings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recording_save_date", models.DateTimeField(auto_now_add=True)),
                (
                    "recording_audio_path",
                    models.FileField(upload_to=audio_recordings_app.models.upload_to),
                ),
            ],
        ),
    ]
